import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"]
})
const oswaldFont = Oswald({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
        rel="logo"
        href="/logo?<generated>"
        type="image/<generated>"
        sizes="<generated>"
        />
      </head>
      <body
        className={`${robotoSlab.className} antialiased bg-background text-text`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
